version: '3.8'

services:
  app:
    build: .
    container_name: ms--betest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=supersecretkey
      - MONGO_URI=mongodb://root:example@mongo:27017/db__betest?authSource=admin
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo:6.0
    container_name: db__betest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  redis:
    image: redis:7.0
    container_name: redis-betest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
